# Generated by Django 5.0 on 2023-12-14 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('datasetID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserEntryRead',
            fields=[
                ('entryId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KymDataEntry',
            fields=[
                ('entryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game'), ('AN', 'Anime')], max_length=2)),
                ('scoreValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.URLField()),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'KymDataEntry',
            },
        ),
        migrations.CreateModel(
            name='RedditDataEntry',
            fields=[
                ('entryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game'), ('AN', 'Anime')], max_length=2)),
                ('scoreValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.URLField()),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'RedditDataEntry',
            },
        ),
        migrations.CreateModel(
            name='TwitterDataEntry',
            fields=[
                ('entryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game'), ('AN', 'Anime')], max_length=2)),
                ('scoreValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lang', models.CharField(max_length=2)),
                ('source', models.CharField(max_length=3)),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'TwitterDataEntry',
            },
        ),
        migrations.CreateModel(
            name='CookieUser',
            fields=[
                ('cookie', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('entriesRead', models.ManyToManyField(null=True, to='ProjectFlashback_b_app.userentryread')),
            ],
        ),
    ]
