# Generated by Django 5.0 on 2023-12-09 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('datasetID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RedditDataEntry',
            fields=[
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game'), ('AN', 'Anime')], max_length=2)),
                ('img', models.URLField()),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'RedditDataEntry',
                'abstract': False,
            },
        ),
    ]
