# Generated by Django 5.0 on 2023-12-13 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('datasetID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KymDataEntry',
            fields=[
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game'), ('AN', 'Anime')], max_length=2)),
                ('img', models.URLField()),
                ('fav', models.IntegerField()),
                ('views', models.IntegerField()),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'KymDataEntry',
            },
        ),
        migrations.CreateModel(
            name='RedditDataEntry',
            fields=[
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game'), ('AN', 'Anime')], max_length=2)),
                ('img', models.URLField()),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'RedditDataEntry',
            },
        ),
        migrations.CreateModel(
            name='TwitterDataEntry',
            fields=[
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game'), ('AN', 'Anime')], max_length=2)),
                ('lang', models.CharField(max_length=2)),
                ('retweetsCount', models.IntegerField()),
                ('likesCount', models.IntegerField()),
                ('source', models.CharField(max_length=3)),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'TwitterDataEntry',
            },
        ),
    ]
