# Generated by Django 5.0 on 2023-12-09 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditdataentry',
            name='url',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='KymDataEntry',
            fields=[
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game'), ('AN', 'Anime')], max_length=2)),
                ('img', models.URLField()),
                ('fav', models.IntegerField()),
                ('views', models.IntegerField()),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'KymDataEntry',
                'abstract': False,
            },
        ),
    ]
