# Generated by Django 5.0 on 2023-12-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntryRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CookieUser',
            fields=[
                ('cookie', models.IntegerField(primary_key=True, serialize=False)),
                ('entriesRead', models.ManyToManyField(to='ProjectFlashback_b_app.userentryread')),
            ],
        ),
    ]
