# Generated by Django 5.0 on 2023-12-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_app', '0002_alter_cookieuser_entriesread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kymdataentry',
            name='entryType',
            field=models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('WK', 'Wikipedia'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game')], max_length=2),
        ),
        migrations.AlterField(
            model_name='redditdataentry',
            name='entryType',
            field=models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('WK', 'Wikipedia'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game')], max_length=2),
        ),
        migrations.AlterField(
            model_name='twitterdataentry',
            name='entryType',
            field=models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('WK', 'Wikipedia'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game')], max_length=2),
        ),
        migrations.CreateModel(
            name='WikipediaDataEntry',
            fields=[
                ('entryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('WK', 'Wikipedia'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game')], max_length=2)),
                ('scoreValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('about', models.CharField(max_length=1000)),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'WikipediaDataEntry',
            },
        ),
    ]
