# Generated by Django 5.0 on 2023-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_app', '0002_userentryread_cookieuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookieuser',
            name='cookie',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
