# Generated by Django 5.0 on 2023-12-10 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_app', '0002_alter_redditdataentry_url_kymdataentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterDataEntry',
            fields=[
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game'), ('AN', 'Anime')], max_length=2)),
                ('lang', models.CharField(max_length=2)),
                ('retweetsCount', models.IntegerField()),
                ('likesCount', models.IntegerField()),
                ('source', models.CharField(max_length=3)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'TwitterDataEntry',
                'abstract': False,
            },
        ),
    ]
