# Generated by Django 5.0 on 2023-12-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_app', '0003_alter_kymdataentry_entrytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipediadataentry',
            name='img',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
