# Generated by Django 5.0 on 2023-12-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_app', '0005_alter_kymdataentry_url_alter_redditdataentry_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImbdbGameDataEntry',
            fields=[
                ('entryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('WK', 'Wikipedia'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game')], max_length=2)),
                ('scoreValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('summary', models.CharField(max_length=1000)),
                ('img', models.URLField()),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'ImbdbGameDataEntry',
            },
        ),
        migrations.CreateModel(
            name='ImbdbMovieDataEntry',
            fields=[
                ('entryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('WK', 'Wikipedia'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game')], max_length=2)),
                ('scoreValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('summary', models.CharField(max_length=1000)),
                ('img', models.URLField()),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'ImbdbMovieDataEntry',
            },
        ),
        migrations.CreateModel(
            name='ImbdbShowDataEntry',
            fields=[
                ('entryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=250)),
                ('entryType', models.CharField(choices=[('RE', 'Reddit'), ('NW', 'News'), ('ME', 'Meme'), ('WK', 'Wikipedia'), ('MV', 'Movie'), ('TV', 'TV Show'), ('SO', 'Song'), ('GA', 'Game')], max_length=2)),
                ('scoreValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('summary', models.CharField(max_length=1000)),
                ('img', models.URLField()),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_app.dataset')),
            ],
            options={
                'db_table': 'ImbdbShowDataEntry',
            },
        ),
    ]
