# Generated by Django 5.0 on 2023-12-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_app', '0006_imbdbgamedataentry_imbdbmoviedataentry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikipediadataentry',
            old_name='about',
            new_name='summary',
        ),
    ]
